### ISSUE TITLE
Cannot impute categorical variables

### ISSUE THREAD

**Issue by AurelieMich** [mayer79/missRanger#11]
I am trying to impute a dataset that contains categorical (factors) and numerical variables and that has about 10 % missing values in each variable. I have been able to impute my dataset with missForest, but I get the error "Error: is.vector(x) is not TRUE" when it comes to imputing my factor variable. 

Is there a way to impute factors with missRanger?

**Comment by mayer79** [comment]
Thanks for playing with missRanger. I can confirm there is a bug if the variable with the least number of missings is a factor. To fix the problem, I have submitted missRanger 1.0.1 to CRAN just now. It will be available within short time.
