### ISSUE TITLE
Replace `cat` with `message`

### ISSUE THREAD

**Issue by talegari** [mayer79/missRanger#12]
Hi Mayer,

This is a great package, Thanks! I am attempting to use `missRanger` function within another, but some `cat` output seems to clutter the output and it is hard to get rid of them. Would `message` be a better option?

**Comment by mayer79** [comment]
Good idea. I also had the impression that little Miss is chatting uncontrollably. We can go for `message`/`suppressMessage` or add a `verbose` argument. I think it would not be a problem in combination with the `verbose` option in `ranger` itself.

**Comment by mayer79** [comment]
I've added that `verbose` argument. Cran release usually takes 0-1 working day. Setting it to 0 will hide all infos, 1 is the default and 2 is providing OOB estimates of the prediction errors of all forests to see the process.
