### ISSUE TITLE
Is there any parallelization option?

### ISSUE THREAD

**Issue by mythicalprogrammer** [mayer79/missRanger#15]
Hi, I was curious if there are any parallelization option since trees in random forest can be build independently unlike boost method. Are there any options within this library that would affect missRanger from being parallelize? Reason why I'm asking because missForest package have an option for it and code example for it was curious if there are any to speed up my imputation.

Thank you for this package

**Comment by mayer79** [comment]
Thx for your interest. MissRanger is built upon the `ranger` package that is already optimized in this respect. So basically, `missRanger` is running on all available cores by default.
