### ISSUE TITLE
Return OOB accuracy

### ISSUE THREAD

**Issue by markgrujic** [mayer79/missRanger#16]
Hi,
Thanks for the work on this package. I can't open a branch to submit a PR, but what do you think of the changes here:
https://gist.github.com/markgrujic/a46a4466b618164e77e0abda14d97590

Note a new argument called returnOOB and the associated code from line 80 that returns a list of the imputed data and OOB accuracy if required.
Cheers

**Comment by mayer79** [comment]
Thx Mark. I will add it very soon. One question: Would it be an option to add the OOB accuracies as an attribute to the data (so that the standard output interface does not change)? I am not yet sure which is more useful.

**Comment by markgrujic** [comment]
Hi, yep attribute would be a great way to do it too. Either way, I'm not fussed.

**Comment by markgrujic** [comment]
Great, works a treat. Sorry for the delay, end of year etc..
Cheers

**Comment by mayer79** [comment]
Now on CRAN
