### ISSUE TITLE
Interface to specify variables to use/impute/ignore.

### ISSUE THREAD

**Issue by mayer79** [mayer79/missRanger#17]
`missRanger` uses all factors and numeric variables in the fitting process. This is annoying if there are id variables etc. that we want to ignore during imputation. Similarly, there might be situations where there is a fixed set of variables X used to fill missing values and a set of variables Y that should be imputed. What is the neatest way to pass this info to `missRanger`?

Suggestion: 

- impute = NULL (or character vector): Variables to impute. If NULL, use all.

- impute_by = NULL (or character vector): Variables used to impute "impute". If NULL, use all.

- impute_ignore: NULL (or character vector): Variables not to impute.

- impute_by_ignore = NULL (or character vector): Variables not used to impute.

Any input is very welcome.

**Comment by mnwright** [comment]
What about a formula interface? 

The default would be `. ~ .`, i.e. impute all by all. 

One could use something like `A + B ~ C + D` or `. -ID -y ~ . -ID`. 

Wouldn't that combine all of your suggestions above in one argument?

**Comment by mayer79** [comment]
Awesome idea!

**Comment by mayer79** [comment]
Ready for cran
