### ISSUE TITLE
Why get "out of bag" error over 1?

### ISSUE THREAD

**Issue by James-Yong-XIANG** [mayer79/missRanger#21]
Hi,

Thx for providing such a nice package for the imputation.

I have a question about the "OOB" error. When conducting multiple imputations on a data frame with (nrow = 4,320, ncol = 596), I got many "OOB" over 1 (max = 1.04). The overall missing rate is 64.61%, But max missing rate for each column is 10.69%. Could someone help me to figure out why the OOB error is over 1.

thx for your help.

**Comment by mayer79** [comment]
OOB error refers to the random forest used to fill the gaps. It is not related to the proportion of missing values. A small OOB error means that the gaps can be filled relatively well by other columns, while a high OOB error means that the gaps are quite randomly filled by the algorithm.

**Comment by James-Yong-XIANG** [comment]
Thx for your reply.

Do you mean it is normal for the OOB over 1? 

And, one more question, what is the appropriate cutoff of OOB error for accept the performance of the imputation?

Thx for your kind help.

**Comment by mayer79** [comment]
Yes, it is normal. No cut-off is required. If a column is independent of the others, random imputation is is good as those from a low accuracy model.
