### ISSUE TITLE
Parallel & progress bars

### ISSUE THREAD

**Issue by joannawolthuis** [mayer79/missRanger#31]
Hi there! I was wondering if there was any way to adapt your algorithm to work in parallel , similarly to missForest. Secondly, I was wondering if there is a way to have some kind of progress bar per iteration (as in percentual rather than the dots). Thanks for your work on this package :)

Cheers,
Joanna

**Comment by mayer79** [comment]
`missRanger()` uses the `ranger` package to fit random forests. `ranger` is fully parallelized, so this cannot be optimized additionally. If you feel that the algorithm is too slow, you can play with different parameters. E.g. you can reduce the numbers of trees from the default of 500 to `num.trees = 100` (-> check the arguments of `ranger()`). `missForest()` uses 100 trees per default.

Good idea to use standard progress bars. I am working on this right now and will soon have it on github.

**Comment by mayer79** [comment]
If you find time, you can test the new progress bar with 

```
devtools::install_github("mayer79/missRanger", subdir = "release/missRanger", ref = "progressbar")
```
