### ISSUE TITLE
Consistent as.character(formula)==3L error

### ISSUE THREAD

**Issue by rjfhoffman** [mayer79/missRanger#41]
Hello,

In the last week, missRanger has been giving an error that "length(formula <- as.character(formula)) == 3L is not TRUE". This error is also coming up when I ran the vignette code to see if it was an issue with my data, but this error comes up every time:

```{r, error=T}
irisImputed <- missRanger(irisWithNA, pmm.k = 3, num.trees = 100, verbose = 0)
irisImputed <- missRanger(irisWithNA, formula= .~.-Species, pmm.k = 3, num.trees = 100, verbose = 0)
```

**Comment by mayer79** [comment]
Thanks for reporting!

**Comment by rjfhoffman** [comment]
After starting a fresh session without including these packages (or other packages that require them) missranger runs again

**Comment by mayer79** [comment]
Perfect. The issue with above package is still unfortunate.
