### ISSUE TITLE
Undefined Columns Selected Error if Strange Variable Names Present

### ISSUE THREAD

**Issue by DarioS** [mayer79/missRanger#51]
If some strange omics identifiers are some of the column names, the imputation fails.

```r
> colnames(iris)[2] <- "IGHV3-43D;IGHV3-9"
> missRanger(iris)
Missing value imputation by random forests
Error in `[.data.frame`(data, , relevantVars[[1L]], drop = FALSE) : 
  undefined columns selected
```

Can you make it more bioinformatics-friendly?

**Comment by mayer79** [comment]
Thanks for reporting. This is a known but unfortunate issue. 

I once attempted to fix it (https://github.com/mayer79/missRanger/issues/19), but could not find a good solution. 

A fix would additionally require to replace `ranger`'s formula interface by the "x/y" interface, which might solve another problem (https://github.com/mayer79/missRanger/issues/50). 

I will keep the issue open. As it is complex, you can't expect a solution soon.

**Comment by mayer79** [comment]
Fixed in https://github.com/mayer79/missRanger/pull/52
