### ISSUE TITLE
How can I change hyperparameters as in ranger?

### ISSUE THREAD

**Issue by NamLQ** [mayer79/missRanger#6]
Hi!

In ranger, I can tweak these arguments: num.trees, mtry, min.node.size, splitrule, and num.random.splits. How can I do so in missRanger?

Thank you very much!

**Comment by mayer79** [comment]
Hello,
At the moment, they are set to a fixed default (usually they work in an okay way). But I will have a look at it. It should not be tricky to implement.

**Comment by mayer79** [comment]
Check now via "install_github" to use `missRanger` with `ranger` defaults. Use the ellipsis "..." to change the defaults.
